language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
script:
  - npm run build
deploy:
  provider: surge
  domain: myreminders.surge.sh
  project: ./build/
on:
  branch: master
