language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
script:
  - yarn build
deploy:
  provider: surge
  domain: myreminders.surge.sh
  local_dir: build
on:
  branch: master
